artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/sabhireddy05091999/wine-/raw/refs/heads/main/winequality-red.csv.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: /Users/santhoshreddy/Downloads/wine project/Wine/artifacts/data_ingestion/winequality-red copy.csv
  STATUS_FILE: artifacts/data_validation/status.txt

